### ISSUE TITLE
Limits changes in groups

### ISSUE THREAD

**Issue by thomgb** [loicsander/Robofont-scripts#14]
[See my filter] (https://github.com/thomgb/RoboFontScripts/tree/master/pens)

I have a tracking filter. Limits are -100 to 100.
In a group the slider goes from 0 to 100.

**Comment by loicsander** [comment]
Ok, tried the exact same thing and my slider has the right limits. 

With this on top of the mode-changing issue, I’m starting to suspect there may be something fishy about the version of vanilla your Robofont works with, although it makes little sense… 

What version of Robofont are you using by the way?

PS: I love it that you did a simple tracking filter, I hadn’t even thought of that, it’s gonna make my Ground Control extension useless :') + I’m starting to think that it could be nice if one could add filters simply by typing little snippets of code directly in the extension rather than linking to a file for 4 lines of code.

**Comment by thomgb** [comment]
I use Robofont 1.6. 
Also just downloaded a fresh copy of the app to make sure I didnt modified something earlier... :)
But same results.

I'll do some test on the snow leopard system. see what its all doing over there. Keep you posted.

PS: directly in the extension would be great!
Sorry to Ground Zero your Ground Control :P ;)

**Comment by thomgb** [comment]
See what I see: https://www.dropbox.com/s/49cdhcywfgj4o1t/issues.mov?dl=0

**Comment by loicsander** [comment]
Now that’s very concrete, thanks!

Your video helped solve the min/max issue on sliders, you shouldn’t encounter that any more.

As for the rest, I did the steps exactly like you and nothing went wrong, the mystery thickens…

**Comment by loicsander** [comment]
I can’t be certain, but I think I might have found the issue that crashed Robofont… check out the last version.

**Comment by thomgb** [comment]
Oh yes! This is solved! Hoorah!
